### ISSUE TITLE
Markbot functionality issues

### ISSUE THREAD

**Issue by matthewpeixoto** [matthewpeixoto/circle-colourer#1]
Website seems to function properly but I'm not sure how to fix the Markbot errors seen below.

![screen shot 2017-05-09 at 5 39 08 pm](https://cloud.githubusercontent.com/assets/16690200/25874021/b5b6a326-34de-11e7-82b9-1f761846dd34.png)

@thomasjbradley

**Comment by thomasjbradley** [comment]
The `$('.ball')` problem is because that doesn’t exist anywhere in your code. You have `.ball:focus` but not `.ball` by itself.

Now, I see you're using `:focus` to highlight the current ball—that's extremely clever, I had never thought of doing it that way. My solution was to add a class to the ball the user clicks on and then use that class to select the ball to colour.

**Comment by matthewpeixoto** [comment]
That all makes perfect sense. Thank you.
